"""
Django settings for django_cms project.

Generated by 'django-admin startproject' using Django 4.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# 4. 静态资源配置：指定本地静态资源目录（关联之前创建的static目录）
BASE_DIR = Path(__file__).resolve().parent.parent.parent  # 修正后：指向django-enterprise-cms根目录

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-e&b3ngit6o+564@ds3_tx^r9goh@ig@&1qfi!uf-1ujm-fy22("

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 2. 允许访问的主机：开发环境宽松配置
ALLOWED_HOSTS = ['127.0.0.1', 'localhost']  # 仅允许本地访问，足够开发使


# Application definition

INSTALLED_APPS = [
    # Django默认内置应用
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 项目核心依赖应用（提前注册，后续开发直接使用）
    'rest_framework',  # DRF（接口开发）
    'django_filters',  # 数据筛选（后续文章/用户列表筛选）
    'corsheaders',     # 跨域处理（后续DRF接口跨域）
    'captcha',         # 图形验证码（后续用户登录/注册）
    'tinymce',         # 富文本编辑（后续文章编辑）
    #'haystack',        # 全文检索（后续文章搜索）

    # 预留自定义应用位置（后续添加apps/users、apps/rbac等，格式：'users'、'rbac'）
    'users',  # 等价于apps.users，因已配置apps目录搜索路径
    'apps.rbac',   # RBAC权限模块应用（新增）
    
    # 第三方扩展应用（新增）
    'django_extensions',
    'rest_framework',  # 新增：注册DRF应用
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'apps.rbac.middleware.RbacPagePermissionMiddleware',  # 新增：RBAC页面级权限中间件    
]

ROOT_URLCONF = "django_cms.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "django_cms.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# 3. 数据库配置：开发环境使用SQLite（无需额外安装，便捷演示）
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',  # 本地SQLite数据库文件，自动生成
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]



# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"



# 静态资源URL
STATIC_URL = '/static/'
# 本地静态资源存放目录（关联项目根目录的static文件夹）
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# 5. 媒体文件配置（用户上传文件，关联之前创建的media目录）
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# 6. 应用注册：添加apps目录的搜索路径（后续业务应用放在apps目录，需让Django识别）
# 找到INSTALLED_APPS配置，在顶部添加以下代码
import sys
# 将apps目录添加到Python搜索路径
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))

# 7. 语言与时区：配置为中文+上海时区（开发更友好）
LANGUAGE_CODE = 'zh-hans'  # 中文简体
TIME_ZONE = 'Asia/Shanghai'  # 上海时区
USE_I18N = True
USE_TZ = True

# 指定自定义用户模型为默认用户模型
AUTH_USER_MODEL = 'users.User'

# DRF全局配置
REST_FRAMEWORK = {
    # 默认认证类（会话认证，适用于前后端不分离；前后端分离可添加JWT认证）
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    # 默认权限类（全局使用RBAC接口权限类）
    'DEFAULT_PERMISSION_CLASSES': [
        'apps.rbac.permissions.RbacApiPermission',
    ],
}
