"""
Django settings for django_cms project.

Generated by 'django-admin startproject' using Django 4.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# 4. 静态资源配置：指定本地静态资源目录（关联之前创建的static目录）
BASE_DIR = Path(__file__).resolve().parent.parent.parent  # 修正后：指向django-enterprise-cms根目录

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# 5. 秘密密钥：生产环境建议使用环境变量配置（避免硬编码泄露）
# 原配置：SECRET_KEY = '你的默认密钥'
# 修改为：从系统环境变量中读取SECRET_KEY
SECRET_KEY = os.environ.get('DJANGO_CMS_SECRET_KEY')  # 线上服务器需配置该环境变量

# 1. DEBUG模式：生产环境必须关闭（避免泄露项目信息）
DEBUG = False

# 2. 允许访问的主机：生产环境指定具体域名/IP，禁止宽松配置
ALLOWED_HOSTS = ['你的域名.com', '你的服务器IP']  # 替换为实际线上域名/IP，多个用逗号分


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "django_cms.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "django_cms.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# 3. 数据库配置：生产环境使用MySQL（性能更优，支持高并发）
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'django_cms_prod',  # 生产环境MySQL数据库名（需提前创建）
        'USER': 'mysql用户名',  # 替换为实际MySQL用户名（如root）
        'PASSWORD': 'mysql密码',  # 替换为实际MySQL密码
        'HOST': 'MySQL服务器地址',  # 本地部署填'127.0.0.1'，远程部署填服务器IP
        'PORT': '3306',  # MySQL默认端口
        'OPTIONS': {
            'charset': 'utf8mb4',  # 支持所有中文编码，避免乱码
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators


AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]



# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"



# 4. 静态资源配置：生产环境收集静态资源到统一目录
STATIC_URL = '/static/'
# 生产环境静态资源收集目录（项目根目录下创建static_collect，无需提前创建，后续用命令收集）
STATIC_ROOT = os.path.join(BASE_DIR, 'static_collect')
# 注释/删除开发环境的STATICFILES_DIRS配置
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'static'),
# ]

# 5. 媒体文件配置（用户上传文件，关联之前创建的media目录）
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# 6. 应用注册：添加apps目录的搜索路径（后续业务应用放在apps目录，需让Django识别）
# 找到INSTALLED_APPS配置，在顶部添加以下代码
import sys
# 将apps目录添加到Python搜索路径
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))

# 7. 语言与时区：配置为中文+上海时区（开发更友好）
LANGUAGE_CODE = 'zh-hans'  # 中文简体
TIME_ZONE = 'Asia/Shanghai'  # 上海时区
USE_I18N = True
USE_TZ = True


# 6. 日志配置：生产环境开启详细日志，便于排查问题（添加到prod.py末尾）
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'ERROR',  # 只记录错误日志
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/django_cms_prod.log'),  # 日志存放路径
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}