# Generated by Django 4.2.17 on 2026-01-04 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbac", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="roles",
            field=models.ManyToManyField(
                blank=True,
                help_text="请为该用户分配对应的角色，可多选",
                related_name="user_roles",
                to="rbac.role",
                verbose_name="用户角色",
            ),
        ),
    ]
