# Generated by Django 4.2.17 on 2026-01-04 02:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission_name",
                    models.CharField(
                        help_text="请输入唯一的权限名称，如：查看用户列表、修改用户状态",
                        max_length=64,
                        unique=True,
                        verbose_name="权限名称",
                    ),
                ),
                (
                    "permission_code",
                    models.CharField(
                        help_text="请输入英文唯一标识，仅含字母、下划线，如：user_view",
                        max_length=64,
                        unique=True,
                        verbose_name="权限标识",
                    ),
                ),
                (
                    "url_path",
                    models.CharField(
                        blank=True,
                        help_text="请输入该权限对应的URL路径，如：/users/login/logs/，可选填",
                        max_length=256,
                        null=True,
                        verbose_name="关联路由",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="请输入权限的详细描述，可选填",
                        null=True,
                        verbose_name="权限描述",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "权限管理",
                "verbose_name_plural": "权限管理",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_name",
                    models.CharField(
                        help_text="请输入唯一的角色名称，如：超级管理员、普通管理员",
                        max_length=32,
                        unique=True,
                        verbose_name="角色名称",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="请输入角色的功能描述，可选填",
                        null=True,
                        verbose_name="角色描述",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="请为该角色分配对应的权限，可多选",
                        related_name="role_permissions",
                        to="rbac.permission",
                        verbose_name="绑定权限",
                    ),
                ),
            ],
            options={
                "verbose_name": "角色管理",
                "verbose_name_plural": "角色管理",
                "ordering": ["-create_time"],
            },
        ),
    ]
